#!/bin/zsh

BIN_PATH=./target/xtensa-esp32-none-elf/debug/examples/blinky

esptool --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 $BIN_PATH.bin